export const SET_HOUSING_STOCK_LIST = 'SET_HOUSING_STOCK_LIST';


export const SET_STREETS_LIST = 'SET_STREETS_LIST';
export const SET_HOUSES_LIST = 'SET_HOUSES_LIST';
export const SET_FLATS_LIST = 'SET_FLATS_LIST';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_ERROR = 'SET_ERROR';
